version: "3.3"

services:
  redis:
    container_name: ok-photos-redis
    image: redis:5.0.3-alpine
  redis_manager:
    container_name: ok-photos-redis-commander
    image: ficusio/redis-commander
    command: ficusio/redis-commander --redis-host redis --redis-port 6379
    ports:
      - 8081:8081
  app:
    build: .
    # build: https://${GITHUB_TOKEN}:@github.com/ikenfin/ok-downloader-bg.git
    command: npm start
    ports:
      - 8080:3000
    # volumes:
    #   - .:/ok-downloader-app/
    depends_on:
      - redis
    env_file:
      - env
    secrets:
      - ok_secret_key
      - ok_public_key
      - ok_app_id
    tmpfs:
      - /run
secrets:
  ok_secret_key:
    file: ../secrets/.ok_secret_key
    # external: true
  ok_public_key:
    file: ../secrets/.ok_public_key
    # external: true
  ok_app_id:
    file: ../secrets/.ok_app_id
    # external: true